[mypy]
ignore_missing_imports = true
warn_return_any = false
warn_unused_ignores = false

[mypy-core.models.*]
ignore_errors = true

[mypy-users.models.*]
ignore_errors = true

[mypy-portfolio.*]
ignore_errors = true

[mypy-blog.*]
ignore_errors = true

[mypy-manage]
ignore_errors = true

[mypy-api_gateway.*]
ignore_errors = true

[mypy-aonware_ai.*]
ignore_errors = true
